#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace ftaa
{
    inline constexpr std::array<char, 8> kProfileMagic = {
        'F', 'T', 'A', 'A', 'P', 'R', 'F', '1'};
    inline constexpr std::uint16_t kProfileFormatMajor = 1;
    inline constexpr std::uint16_t kProfileFormatMinor = 0;
    inline constexpr std::uint8_t kProfileFeatureTemporalAa = 0x01;
    inline constexpr std::uint8_t kProfileFeaturePostProcessSharpen = 0x02;
    inline constexpr std::uint8_t kProfileRequiredFeatures =
        kProfileFeatureTemporalAa | kProfileFeaturePostProcessSharpen;

    enum class ProfileRendererAccessMode : std::uint8_t
    {
        VirtualGetter = 0,
        DirectOwnerPointer = 1
    };

#pragma pack(push, 1)
    // Fixed-size, little-endian authorization record generated by the offline
    // updater. profileSha256 covers every byte preceding that field. The ASI
    // additionally checks the executable identity and independently re-runs
    // the structural locator, so this digest is corruption detection rather
    // than a security boundary.
    struct ProfileFileV1
    {
        std::array<char, 8> magic{};
        std::uint16_t formatMajor = 0;
        std::uint16_t formatMinor = 0;
        std::uint32_t structureSize = 0;
        std::uint32_t imageSize = 0;
        std::uint64_t executableFileSize = 0;
        std::array<std::uint8_t, 32> executableSha256{};

        ProfileRendererAccessMode rendererAccessMode =
            ProfileRendererAccessMode::VirtualGetter;
        std::uint8_t taaActionId = 0;
        std::uint8_t sharpenActionId = 0;
        std::uint8_t featureFlags = 0;
        std::uint32_t reserved0 = 0;

        std::uint64_t registrationRva = 0;
        std::uint64_t switchHandlerRva = 0;
        std::uint64_t taaWrapperRva = 0;
        std::uint64_t sharpenWrapperRva = 0;

        std::uint32_t actionOwnerOffset = 0;
        std::uint32_t getRendererVtableOffset = 0;
        std::uint32_t rendererPointerOffset = 0;
        std::uint32_t switchHandlerVtableOffset = 0;
        std::uint32_t settingsPointerOffset = 0;
        std::uint32_t temporalAaFlagOffset = 0;
        std::uint32_t postProcessSharpenFlagOffset = 0;

        std::array<std::uint8_t, 16> reserved1{};
        std::array<std::uint8_t, 32> profileSha256{};
    };
#pragma pack(pop)

    inline constexpr std::size_t kProfileHashedSize =
        offsetof(ProfileFileV1, profileSha256);

    static_assert(sizeof(ProfileFileV1) == 176);
    static_assert(kProfileHashedSize == 144);
}
