if(NOT DEFINED INPUT OR NOT EXISTS "${INPUT}")
    message(FATAL_ERROR "The companion ASI was not built: ${INPUT}")
endif()
if(NOT DEFINED OUTPUT)
    message(FATAL_ERROR "No embedded-resource output path was supplied.")
endif()

get_filename_component(output_directory "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(TO_CMAKE_PATH "${INPUT}" normalized_input)
file(WRITE "${OUTPUT}" "101 RCDATA \"${normalized_input}\"\n")
